# https://github.com/sw-yx/gh-action-data-scraping
on:
  schedule:
    - cron:  '0 8 * * *' # every day at 8am
name: Pull Data and Save it
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Scrape
      run: npm run githubGetAllData 
      env:
        GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }} # get this from a github oauth app you set up
        GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you